call validate_and_insert_tag('PhD Studentship ');
call validate_and_insert_tag('Postdoctoral');
call validate_and_insert_tag('Fellowship');
call validate_and_insert_tag('Research Associate');
call validate_and_insert_tag('Senior Scientist');
call validate_and_insert_tag('Research Fellow ');
call validate_and_insert_tag('Other');
call validate_and_insert_tag('Biological and Medical Sciences');
call validate_and_insert_tag('Agricultural Sciences');
call validate_and_insert_tag('Biochemistry');
call validate_and_insert_tag('Bioinformatics');
call validate_and_insert_tag('Biomedical Engineering');
call validate_and_insert_tag('Biophysics');
call validate_and_insert_tag('Biotechnology');
call validate_and_insert_tag('Botany / Plant Science');
call validate_and_insert_tag('Cancer / Oncology');
call validate_and_insert_tag('Cell Biology / Development');
call validate_and_insert_tag('Dentistry');
call validate_and_insert_tag('Ecology and Conservation');
call validate_and_insert_tag('Endocrinology');
call validate_and_insert_tag('Evolution');
call validate_and_insert_tag('Food Science / Nutrition');
call validate_and_insert_tag('Genetics');
call validate_and_insert_tag('Immunology');
call validate_and_insert_tag('Marine Biology');
call validate_and_insert_tag('Medical / Biomedical Physics');
call validate_and_insert_tag('Medical / Clinical Science');
call validate_and_insert_tag('Microbiology');
call validate_and_insert_tag('Molecular Biology');
call validate_and_insert_tag('Neuroscience / Neurology');
call validate_and_insert_tag('Obstetrics\, Gynaecology and Reproduction');
call validate_and_insert_tag('Parasitology');
call validate_and_insert_tag('Pathology');
call validate_and_insert_tag('Pharmacology / Toxicology');
call validate_and_insert_tag('Physiology and Sports Science');
call validate_and_insert_tag('Psychology and Psychiatry');
call validate_and_insert_tag('Public Health and Epidemiology');
call validate_and_insert_tag('Structural Biology');
call validate_and_insert_tag('Veterinary Medicine');
call validate_and_insert_tag('Virology');
call validate_and_insert_tag('Zoology / Animal Science');
call validate_and_insert_tag('Physical Sciences');
call validate_and_insert_tag('Applied Physics');
call validate_and_insert_tag('Astrophysics');
call validate_and_insert_tag('Atmospheric Physics');
call validate_and_insert_tag('Atomic Physics');
call validate_and_insert_tag('Biophysics');
call validate_and_insert_tag('Condensed Matter Physics');
call validate_and_insert_tag('Fluid Dynamics');
call validate_and_insert_tag('Geophysics');
call validate_and_insert_tag('Low-temperature Physics');
call validate_and_insert_tag('Materials Science');
call validate_and_insert_tag('Medical / Biomedical Physics');
call validate_and_insert_tag('Metrology');
call validate_and_insert_tag('Nuclear Physics');
call validate_and_insert_tag('Optical Physics');
call validate_and_insert_tag('Particle Physics');
call validate_and_insert_tag('Plasma Physics');
call validate_and_insert_tag('Radiation');
call validate_and_insert_tag('Semiconductors');
call validate_and_insert_tag('Theoretical Physics');
call validate_and_insert_tag('Engineering');
call validate_and_insert_tag('Acoustics');
call validate_and_insert_tag('Aeronautical Engineering');
call validate_and_insert_tag('Biomedical Engineering');
call validate_and_insert_tag('Chemical Engineering');
call validate_and_insert_tag('Civil and Structural Engineering');
call validate_and_insert_tag('Electrical and Electronic');
call validate_and_insert_tag('Energy');
call validate_and_insert_tag('Manufacturing');
call validate_and_insert_tag('Materials Science');
call validate_and_insert_tag('Mechanical Engineering');
call validate_and_insert_tag('Nanotechnology');
call validate_and_insert_tag('Nuclear Engineering');
call validate_and_insert_tag('Semiconductors');
call validate_and_insert_tag('Software Engineering');
call validate_and_insert_tag('Telecommunications');
call validate_and_insert_tag('Humanities');
call validate_and_insert_tag('American Studies');
call validate_and_insert_tag('Anthropology');
call validate_and_insert_tag('Archaeology');
call validate_and_insert_tag('Architecture and the Built Environment');
call validate_and_insert_tag('Asian Studies');
call validate_and_insert_tag('Classics and Ancient History');
call validate_and_insert_tag('Communication\, Cultural and Media Studies');
call validate_and_insert_tag('European Studies');
call validate_and_insert_tag('Geography');
call validate_and_insert_tag('History');
call validate_and_insert_tag('Middle East and African Studies');
call validate_and_insert_tag('Modern Languages and Linguistics');
call validate_and_insert_tag('Philosophy');
call validate_and_insert_tag('Theology and Religious Studies');
call validate_and_insert_tag('Business and Finance');
call validate_and_insert_tag('Accounting and Finance');
call validate_and_insert_tag('Business and Management');
call validate_and_insert_tag('Economics');
call validate_and_insert_tag('Tourism and Hospitality');
call validate_and_insert_tag('Arts');
call validate_and_insert_tag('Architecture and the Built Environment');
call validate_and_insert_tag('Art and Design');
call validate_and_insert_tag('Classics and Ancient History');
call validate_and_insert_tag('Drama\, Dance and Performing Arts');
call validate_and_insert_tag('English');
call validate_and_insert_tag('History');
call validate_and_insert_tag('Music');
call validate_and_insert_tag('Chemical Sciences');
call validate_and_insert_tag('Agricultural Chemistry');
call validate_and_insert_tag('Analytical Chemistry');
call validate_and_insert_tag('Biochemistry');
call validate_and_insert_tag('Chemical Engineering');
call validate_and_insert_tag('Chemical Toxicology');
call validate_and_insert_tag('Computational Chemistry');
call validate_and_insert_tag('Electrochemistry');
call validate_and_insert_tag('Environmental Chemistry');
call validate_and_insert_tag('Food Chemistry');
call validate_and_insert_tag('Geochemistry');
call validate_and_insert_tag('Inorganic Chemistry');
call validate_and_insert_tag('Macromolecular Chemistry');
call validate_and_insert_tag('Materials Science');
call validate_and_insert_tag('Organic Chemistry');
call validate_and_insert_tag('Pharmaceutical Chemistry');
call validate_and_insert_tag('Physical Chemistry');
call validate_and_insert_tag('Synthetic Chemistry');
call validate_and_insert_tag('Earth Sciences');
call validate_and_insert_tag('Agronomy and Soil Science');
call validate_and_insert_tag('Atmospheric Physics');
call validate_and_insert_tag('Climatology and Climate Change');
call validate_and_insert_tag('Ecology and Conservation');
call validate_and_insert_tag('Ecotoxicology and Pollution');
call validate_and_insert_tag('Environmental Chemistry');
call validate_and_insert_tag('Environmental Science');
call validate_and_insert_tag('Geochemistry');
call validate_and_insert_tag('Geography');
call validate_and_insert_tag('Geology');
call validate_and_insert_tag('Geophysics');
call validate_and_insert_tag('Hydrology');
call validate_and_insert_tag('Meteorology');
call validate_and_insert_tag('Maths and Computing');
call validate_and_insert_tag('Applied Mathematics');
call validate_and_insert_tag('Bioinformatics');
call validate_and_insert_tag('Computational Chemistry');
call validate_and_insert_tag('Computer Science and IT');
call validate_and_insert_tag('Data Analysis');
call validate_and_insert_tag('Information Science');
call validate_and_insert_tag('Mathematics');
call validate_and_insert_tag('Operational Research');
call validate_and_insert_tag('Software Engineering');
call validate_and_insert_tag('Statistics');
call validate_and_insert_tag('Social Science and Health');
call validate_and_insert_tag('American Studies');
call validate_and_insert_tag('Anthropology');
call validate_and_insert_tag('Architecture and the Built Environment');
call validate_and_insert_tag('Asian Studies');
call validate_and_insert_tag('Development Studies');
call validate_and_insert_tag('Economics');
call validate_and_insert_tag('Education');
call validate_and_insert_tag('European Studies');
call validate_and_insert_tag('Gender and Sexuality');
call validate_and_insert_tag('Geography');
call validate_and_insert_tag('Health Sciences');
call validate_and_insert_tag('History');
call validate_and_insert_tag('Middle East and African Studies');
call validate_and_insert_tag('Modern Languages and Linguistics');
call validate_and_insert_tag('Nursing\, Midwifery and Allied Health Professions');
call validate_and_insert_tag('Philosophy');
call validate_and_insert_tag('Political Science and International Studies');
call validate_and_insert_tag('Psychology');
call validate_and_insert_tag('Public Health and Epidemiology');
call validate_and_insert_tag('Social Work\, Social Policy and Administration');
call validate_and_insert_tag('Sociology');
call validate_and_insert_tag('Sports\, Recreation and Leisure Studies');
call validate_and_insert_tag('Town and Country Planning');
call validate_and_insert_tag('Law');
call validate_and_insert_tag('Aberdeen University');
call validate_and_insert_tag('Aberystwyth University');
call validate_and_insert_tag('Arizona State University');
call validate_and_insert_tag('Aston University');
call validate_and_insert_tag('Babraham Institute');
call validate_and_insert_tag('Bangor University');
call validate_and_insert_tag('Bournemouth University');
call validate_and_insert_tag('Brighton and Sussex Medical School');
call validate_and_insert_tag('Brunel University');
call validate_and_insert_tag('Cardiff University');
call validate_and_insert_tag('Chalmers University of Technology');
call validate_and_insert_tag('Charité - Universitätsmedizin Berlin');
call validate_and_insert_tag('Cranfield University');
call validate_and_insert_tag('Deakin University');
call validate_and_insert_tag('Durham University');
call validate_and_insert_tag('Ecole Polytechnique Federale de Lausanne \(EPFL\)');
call validate_and_insert_tag('Edinburgh Napier University');
call validate_and_insert_tag('Eindhoven University of Technology');
call validate_and_insert_tag('ESRF');
call validate_and_insert_tag('ESSEC Business School');
call validate_and_insert_tag('European Molecular Biology Laboratory \(Grenoble\)');
call validate_and_insert_tag('European Molecular Biology Laboratory \(Hamburg\)');
call validate_and_insert_tag('European Molecular Biology Laboratory \(Heidelberg\)');
call validate_and_insert_tag('European Molecular Biology Laboratory \(Hinxton\)');
call validate_and_insert_tag('European Molecular Biology Laboratory \(Monterotondo\)');
call validate_and_insert_tag('Fraunhofer Heinrich Hertz Institut');
call validate_and_insert_tag('Goldsmiths\, University of London');
call validate_and_insert_tag('Heriot-Watt University');
call validate_and_insert_tag('Horizons University');
call validate_and_insert_tag('Imperial College London');
call validate_and_insert_tag('IMT Institute for Advanced Studies Lucca');
call validate_and_insert_tag('INRS-EMT');
call validate_and_insert_tag('Institut Laue-Langevin');
call validate_and_insert_tag('Institute of Education\, University of London');
call validate_and_insert_tag('ISI Foundation');
call validate_and_insert_tag('John Innes Centre');
call validate_and_insert_tag('Keele University');
call validate_and_insert_tag('King\'s College London');
call validate_and_insert_tag('Kingston University');
call validate_and_insert_tag('KU Leuven');
call validate_and_insert_tag('Kyushu University');
call validate_and_insert_tag('Lancaster University');
call validate_and_insert_tag('Leeds Metropolitan University');
call validate_and_insert_tag('Life Science Zurich Graduate School');
call validate_and_insert_tag('Liverpool John Moores University');
call validate_and_insert_tag('London School of Economics and Political Science');
call validate_and_insert_tag('London South Bank University');
call validate_and_insert_tag('Loughborough University');
call validate_and_insert_tag('Macquarie University');
call validate_and_insert_tag('Manchester Metropolitan University');
call validate_and_insert_tag('Max Planck');
call validate_and_insert_tag('Medical Research Council \(Cambridge\)');
call validate_and_insert_tag('Medical Research Council \(Nottingham\)');
call validate_and_insert_tag('Monash University');
call validate_and_insert_tag('Moredun Research Institute');
call validate_and_insert_tag('National Institute of Agricultural Botany \(NIAB\)');
call validate_and_insert_tag('National University of Singapore');
call validate_and_insert_tag('Newcastle University');
call validate_and_insert_tag('NHH - The Norwegian School of Economics and Business Administration');
call validate_and_insert_tag('Northumbria University');
call validate_and_insert_tag('Nottingham Trent University');
call validate_and_insert_tag('Open University');
call validate_and_insert_tag('Oxford Brookes University');
call validate_and_insert_tag('Politecnico di Milano');
call validate_and_insert_tag('Public Health England');
call validate_and_insert_tag('Queen Mary\, University of London');
call validate_and_insert_tag('Queen\'s University Belfast');
call validate_and_insert_tag('Queensland University of Technology');
call validate_and_insert_tag('Royal Holloway\, University of London');
call validate_and_insert_tag('School of Advanced Study');
call validate_and_insert_tag('Science and Technology Facilities Council');
call validate_and_insert_tag('SRUC - Scotland\'s Rural College');
call validate_and_insert_tag('Swansea University');
call validate_and_insert_tag('Syracuse University');
call validate_and_insert_tag('Teesside University');
call validate_and_insert_tag('The Genome Analysis Centre');
call validate_and_insert_tag('The James Hutton Institute');
call validate_and_insert_tag('Trinity College Dublin');
call validate_and_insert_tag('United Nations University');
call validate_and_insert_tag('Università degli Studi Mediterranea di Reggio Calabria');
call validate_and_insert_tag('Universität Bonn');
call validate_and_insert_tag('Université de Sherbrooke');
call validate_and_insert_tag('Université de Toulouse');
call validate_and_insert_tag('University College Dublin');
call validate_and_insert_tag('University College London');
call validate_and_insert_tag('University of Arkansas');
call validate_and_insert_tag('University of Auckland');
call validate_and_insert_tag('University of Bath');
call validate_and_insert_tag('University of Bern');
call validate_and_insert_tag('University of Birmingham');
call validate_and_insert_tag('University of Bristol');
call validate_and_insert_tag('University of Calgary');
call validate_and_insert_tag('University of Cambridge');
call validate_and_insert_tag('University of Canterbury');
call validate_and_insert_tag('University of Copenhagen');
call validate_and_insert_tag('University of Derby');
call validate_and_insert_tag('University of Dundee');
call validate_and_insert_tag('University of East Anglia');
call validate_and_insert_tag('University of Edinburgh');
call validate_and_insert_tag('University of Essex');
call validate_and_insert_tag('University of Exeter');
call validate_and_insert_tag('University of Genoa');
call validate_and_insert_tag('University of Glasgow');
call validate_and_insert_tag('University of Greenwich');
call validate_and_insert_tag('University of Hull');
call validate_and_insert_tag('University of Kent');
call validate_and_insert_tag('University of Koblenz-Landau');
call validate_and_insert_tag('University of Leeds');
call validate_and_insert_tag('University of Leicester');
call validate_and_insert_tag('University of Lincoln');
call validate_and_insert_tag('University of Liverpool');
call validate_and_insert_tag('University of London');
call validate_and_insert_tag('University of Luxembourg');
call validate_and_insert_tag('University of Macedonia');
call validate_and_insert_tag('University of Manchester');
call validate_and_insert_tag('University of Milan');
call validate_and_insert_tag('University of Nottingham');
call validate_and_insert_tag('University of Otago');
call validate_and_insert_tag('University of Oxford');
call validate_and_insert_tag('University of Portsmouth');
call validate_and_insert_tag('University of Reading');
call validate_and_insert_tag('University of Roehampton');
call validate_and_insert_tag('University of Salford');
call validate_and_insert_tag('University of Sheffield');
call validate_and_insert_tag('University of South Wales');
call validate_and_insert_tag('University of Southampton');
call validate_and_insert_tag('University of St Andrews');
call validate_and_insert_tag('University of Stirling');
call validate_and_insert_tag('University of Strathclyde');
call validate_and_insert_tag('University of Sunderland');
call validate_and_insert_tag('University of Surrey');
call validate_and_insert_tag('University of Sussex');
call validate_and_insert_tag('University of Tartu');
call validate_and_insert_tag('University of the Highlands and Islands');
call validate_and_insert_tag('University of the West of Scotland');
call validate_and_insert_tag('University of the Western Cape');
call validate_and_insert_tag('University of Tübingen');
call validate_and_insert_tag('University of Ulster');
call validate_and_insert_tag('University of Warwick');
call validate_and_insert_tag('University of Western Australia');
call validate_and_insert_tag('University of Western Sydney');
call validate_and_insert_tag('University of Wolverhampton');
call validate_and_insert_tag('University of York');
call validate_and_insert_tag('University of Zurich');
call validate_and_insert_tag('Utah State University\, USA');
call validate_and_insert_tag('Victoria University of Wellington');
call validate_and_insert_tag('Waterford Institute of Technology');
call validate_and_insert_tag('World Maritime University');
call validate_and_insert_tag('Xi\'an Jiaotong-Liverpool University');
call validate_and_insert_tag('York St John University');