call validate_and_insert_badge('Editor','First edit','bronze');
call validate_and_insert_badge('Supporter','First up vote','bronze');
call validate_and_insert_badge('Student','Asked first question with at least one up vote','bronze');
call validate_and_insert_badge('Teacher','Answered first question with at least one up vote','bronze');
call validate_and_insert_badge('Popular Question','Asked a question with 1,000 views','bronze');
call validate_and_insert_badge('Scholar','First accepted answer on your own question','bronze');
call validate_and_insert_badge('Commentator','Left 10 comments','bronze');
call validate_and_insert_badge('Yearling','Active member for a year, earning at least 200 reputation','silver');
call validate_and_insert_badge('Autobiographer','Completed all user profile fields','bronze');
call validate_and_insert_badge('Nice Answer','Answer voted up 10 times','bronze');
call validate_and_insert_badge('Notable Question','Asked a question with 2,500 views','silver');
call validate_and_insert_badge('Nice Question','Question voted up 10 times','bronze');
call validate_and_insert_badge('Critic','First down vote','bronze');
call validate_and_insert_badge('Organizer','First retag','bronze');
call validate_and_insert_badge('Enthusiast','Visited the site each day for 30 days','silver');
call validate_and_insert_badge('Necromancer','Answered a question more than 60 days later with at least 5 votes','silver');
call validate_and_insert_badge('Enlightened','First answer was accepted with at least 10 up votes','silver');
call validate_and_insert_badge('Civic Duty','Voted 300 times','silver');
call validate_and_insert_badge('Self-Learner','Answered your own question with at least 3 up votes','bronze');
call validate_and_insert_badge('Famous Question','Asked a question with 5,000 view','gold');
call validate_and_insert_badge('Taxonomist','Created a tag used by 50 questions','silver');
call validate_and_insert_badge('Citizen Patrol','First flagged post','bronze');
call validate_and_insert_badge('Fanatic','Visited the site each day for 100 days','gold');
call validate_and_insert_badge(' Cleanup','First rollback','bronze');
call validate_and_insert_badge('Good Question','Question voted up 25 times','silver');
call validate_and_insert_badge('Mortarboard','Hit the daily reputation cap for the first time','bronze');
call validate_and_insert_badge('Pundit','Left a comment with score of 10 or more','silver');
call validate_and_insert_badge(' Favorite Question','Question favorited by 25 users','silver');
call validate_and_insert_badge('Guru','Accepted answer and voted up 40 times','silver');
call validate_and_insert_badge('Disciplined','Deleted own post with score of 3 or higher','silver');
call validate_and_insert_badge('Strunk & White','Edited 100 entries','silver');
call validate_and_insert_badge('Peer Pressure','Deleted own post with score of -3 or lower','bronze');
call validate_and_insert_badge('Great Question','Question voted up 100 times','gold');
call validate_and_insert_badge('Legendary','Hit the daily reputation cap on 150 days','gold');
call validate_and_insert_badge('Reversal','Provided answer of +20 score to a question of -5 score','bronze');
call validate_and_insert_badge('Populist','Provided an answer that outscored an accepted answer with 10 votes by 2x','bronze');
call validate_and_insert_badge('Stellar Question','Question favorited by 100 users','bronze');
call validate_and_insert_badge('Great Answer','Answer voted up 100 times','bronze');
call validate_and_insert_badge('Beta Tester','Participated in the BioStar public beta test. Thank you!','bronze');
call validate_and_insert_badge('Epic','Hit the daily reputation cap on 50 days','silver');