insert into tag (tag_name) values ('PhD Studentship ');
insert into tag (tag_name) values ('Postdoctoral');
insert into tag (tag_name) values ('Fellowship');
insert into tag (tag_name) values ('Research Associate');
insert into tag (tag_name) values ('Senior Scientist');
insert into tag (tag_name) values ('Research Fellow ');
insert into tag (tag_name) values ('Other');
insert into tag (tag_name) values ('Biological and Medical Sciences');
insert into tag (tag_name) values ('Agricultural Sciences');
insert into tag (tag_name) values ('Biochemistry');
insert into tag (tag_name) values ('Bioinformatics');
insert into tag (tag_name) values ('Biomedical Engineering');
insert into tag (tag_name) values ('Biophysics');
insert into tag (tag_name) values ('Biotechnology');
insert into tag (tag_name) values ('Botany / Plant Science');
insert into tag (tag_name) values ('Cancer / Oncology');
insert into tag (tag_name) values ('Cell Biology / Development');
insert into tag (tag_name) values ('Dentistry');
insert into tag (tag_name) values ('Ecology and Conservation');
insert into tag (tag_name) values ('Endocrinology');
insert into tag (tag_name) values ('Evolution');
insert into tag (tag_name) values ('Food Science / Nutrition');
insert into tag (tag_name) values ('Genetics');
insert into tag (tag_name) values ('Immunology');
insert into tag (tag_name) values ('Marine Biology');
insert into tag (tag_name) values ('Medical / Biomedical Physics');
insert into tag (tag_name) values ('Medical / Clinical Science');
insert into tag (tag_name) values ('Microbiology');
insert into tag (tag_name) values ('Molecular Biology');
insert into tag (tag_name) values ('Neuroscience / Neurology');
insert into tag (tag_name) values ('Obstetrics\, Gynaecology and Reproduction');
insert into tag (tag_name) values ('Parasitology');
insert into tag (tag_name) values ('Pathology');
insert into tag (tag_name) values ('Pharmacology / Toxicology');
insert into tag (tag_name) values ('Physiology and Sports Science');
insert into tag (tag_name) values ('Psychology and Psychiatry');
insert into tag (tag_name) values ('Public Health and Epidemiology');
insert into tag (tag_name) values ('Structural Biology');
insert into tag (tag_name) values ('Veterinary Medicine');
insert into tag (tag_name) values ('Virology');
insert into tag (tag_name) values ('Zoology / Animal Science');
insert into tag (tag_name) values ('Physical Sciences');
insert into tag (tag_name) values ('Applied Physics');
insert into tag (tag_name) values ('Astrophysics');
insert into tag (tag_name) values ('Atmospheric Physics');
insert into tag (tag_name) values ('Atomic Physics');
insert into tag (tag_name) values ('Biophysics');
insert into tag (tag_name) values ('Condensed Matter Physics');
insert into tag (tag_name) values ('Fluid Dynamics');
insert into tag (tag_name) values ('Geophysics');
insert into tag (tag_name) values ('Low-temperature Physics');
insert into tag (tag_name) values ('Materials Science');
insert into tag (tag_name) values ('Medical / Biomedical Physics');
insert into tag (tag_name) values ('Metrology');
insert into tag (tag_name) values ('Nuclear Physics');
insert into tag (tag_name) values ('Optical Physics');
insert into tag (tag_name) values ('Particle Physics');
insert into tag (tag_name) values ('Plasma Physics');
insert into tag (tag_name) values ('Radiation');
insert into tag (tag_name) values ('Semiconductors');
insert into tag (tag_name) values ('Theoretical Physics');
insert into tag (tag_name) values ('Engineering');
insert into tag (tag_name) values ('Acoustics');
insert into tag (tag_name) values ('Aeronautical Engineering');
insert into tag (tag_name) values ('Biomedical Engineering');
insert into tag (tag_name) values ('Chemical Engineering');
insert into tag (tag_name) values ('Civil and Structural Engineering');
insert into tag (tag_name) values ('Electrical and Electronic');
insert into tag (tag_name) values ('Energy');
insert into tag (tag_name) values ('Manufacturing');
insert into tag (tag_name) values ('Materials Science');
insert into tag (tag_name) values ('Mechanical Engineering');
insert into tag (tag_name) values ('Nanotechnology');
insert into tag (tag_name) values ('Nuclear Engineering');
insert into tag (tag_name) values ('Semiconductors');
insert into tag (tag_name) values ('Software Engineering');
insert into tag (tag_name) values ('Telecommunications');
insert into tag (tag_name) values ('Humanities');
insert into tag (tag_name) values ('American Studies');
insert into tag (tag_name) values ('Anthropology');
insert into tag (tag_name) values ('Archaeology');
insert into tag (tag_name) values ('Architecture and the Built Environment');
insert into tag (tag_name) values ('Asian Studies');
insert into tag (tag_name) values ('Classics and Ancient History');
insert into tag (tag_name) values ('Communication\, Cultural and Media Studies');
insert into tag (tag_name) values ('European Studies');
insert into tag (tag_name) values ('Geography');
insert into tag (tag_name) values ('History');
insert into tag (tag_name) values ('Middle East and African Studies');
insert into tag (tag_name) values ('Modern Languages and Linguistics');
insert into tag (tag_name) values ('Philosophy');
insert into tag (tag_name) values ('Theology and Religious Studies');
insert into tag (tag_name) values ('Business and Finance');
insert into tag (tag_name) values ('Accounting and Finance');
insert into tag (tag_name) values ('Business and Management');
insert into tag (tag_name) values ('Economics');
insert into tag (tag_name) values ('Tourism and Hospitality');
insert into tag (tag_name) values ('Arts');
insert into tag (tag_name) values ('Architecture and the Built Environment');
insert into tag (tag_name) values ('Art and Design');
insert into tag (tag_name) values ('Classics and Ancient History');
insert into tag (tag_name) values ('Drama\, Dance and Performing Arts');
insert into tag (tag_name) values ('English');
insert into tag (tag_name) values ('History');
insert into tag (tag_name) values ('Music');
insert into tag (tag_name) values ('Chemical Sciences');
insert into tag (tag_name) values ('Agricultural Chemistry');
insert into tag (tag_name) values ('Analytical Chemistry');
insert into tag (tag_name) values ('Biochemistry');
insert into tag (tag_name) values ('Chemical Engineering');
insert into tag (tag_name) values ('Chemical Toxicology');
insert into tag (tag_name) values ('Computational Chemistry');
insert into tag (tag_name) values ('Electrochemistry');
insert into tag (tag_name) values ('Environmental Chemistry');
insert into tag (tag_name) values ('Food Chemistry');
insert into tag (tag_name) values ('Geochemistry');
insert into tag (tag_name) values ('Inorganic Chemistry');
insert into tag (tag_name) values ('Macromolecular Chemistry');
insert into tag (tag_name) values ('Materials Science');
insert into tag (tag_name) values ('Organic Chemistry');
insert into tag (tag_name) values ('Pharmaceutical Chemistry');
insert into tag (tag_name) values ('Physical Chemistry');
insert into tag (tag_name) values ('Synthetic Chemistry');
insert into tag (tag_name) values ('Earth Sciences');
insert into tag (tag_name) values ('Agronomy and Soil Science');
insert into tag (tag_name) values ('Atmospheric Physics');
insert into tag (tag_name) values ('Climatology and Climate Change');
insert into tag (tag_name) values ('Ecology and Conservation');
insert into tag (tag_name) values ('Ecotoxicology and Pollution');
insert into tag (tag_name) values ('Environmental Chemistry');
insert into tag (tag_name) values ('Environmental Science');
insert into tag (tag_name) values ('Geochemistry');
insert into tag (tag_name) values ('Geography');
insert into tag (tag_name) values ('Geology');
insert into tag (tag_name) values ('Geophysics');
insert into tag (tag_name) values ('Hydrology');
insert into tag (tag_name) values ('Meteorology');
insert into tag (tag_name) values ('Maths and Computing');
insert into tag (tag_name) values ('Applied Mathematics');
insert into tag (tag_name) values ('Bioinformatics');
insert into tag (tag_name) values ('Computational Chemistry');
insert into tag (tag_name) values ('Computer Science and IT');
insert into tag (tag_name) values ('Data Analysis');
insert into tag (tag_name) values ('Information Science');
insert into tag (tag_name) values ('Mathematics');
insert into tag (tag_name) values ('Operational Research');
insert into tag (tag_name) values ('Software Engineering');
insert into tag (tag_name) values ('Statistics');
insert into tag (tag_name) values ('Social Science and Health');
insert into tag (tag_name) values ('American Studies');
insert into tag (tag_name) values ('Anthropology');
insert into tag (tag_name) values ('Architecture and the Built Environment');
insert into tag (tag_name) values ('Asian Studies');
insert into tag (tag_name) values ('Development Studies');
insert into tag (tag_name) values ('Economics');
insert into tag (tag_name) values ('Education');
insert into tag (tag_name) values ('European Studies');
insert into tag (tag_name) values ('Gender and Sexuality');
insert into tag (tag_name) values ('Geography');
insert into tag (tag_name) values ('Health Sciences');
insert into tag (tag_name) values ('History');
insert into tag (tag_name) values ('Middle East and African Studies');
insert into tag (tag_name) values ('Modern Languages and Linguistics');
insert into tag (tag_name) values ('Nursing\, Midwifery and Allied Health Professions');
insert into tag (tag_name) values ('Philosophy');
insert into tag (tag_name) values ('Political Science and International Studies');
insert into tag (tag_name) values ('Psychology');
insert into tag (tag_name) values ('Public Health and Epidemiology');
insert into tag (tag_name) values ('Social Work\, Social Policy and Administration');
insert into tag (tag_name) values ('Sociology');
insert into tag (tag_name) values ('Sports\, Recreation and Leisure Studies');
insert into tag (tag_name) values ('Town and Country Planning');
insert into tag (tag_name) values ('Law');
insert into tag (tag_name) values ('Aberdeen University');
insert into tag (tag_name) values ('Aberystwyth University');
insert into tag (tag_name) values ('Arizona State University');
insert into tag (tag_name) values ('Aston University');
insert into tag (tag_name) values ('Babraham Institute');
insert into tag (tag_name) values ('Bangor University');
insert into tag (tag_name) values ('Bournemouth University');
insert into tag (tag_name) values ('Brighton and Sussex Medical School');
insert into tag (tag_name) values ('Brunel University');
insert into tag (tag_name) values ('Cardiff University');
insert into tag (tag_name) values ('Chalmers University of Technology');
insert into tag (tag_name) values ('Charité - Universitätsmedizin Berlin');
insert into tag (tag_name) values ('Cranfield University');
insert into tag (tag_name) values ('Deakin University');
insert into tag (tag_name) values ('Durham University');
insert into tag (tag_name) values ('Ecole Polytechnique Federale de Lausanne \(EPFL\)');
insert into tag (tag_name) values ('Edinburgh Napier University');
insert into tag (tag_name) values ('Eindhoven University of Technology');
insert into tag (tag_name) values ('ESRF');
insert into tag (tag_name) values ('ESSEC Business School');
insert into tag (tag_name) values ('European Molecular Biology Laboratory \(Grenoble\)');
insert into tag (tag_name) values ('European Molecular Biology Laboratory \(Hamburg\)');
insert into tag (tag_name) values ('European Molecular Biology Laboratory \(Heidelberg\)');
insert into tag (tag_name) values ('European Molecular Biology Laboratory \(Hinxton\)');
insert into tag (tag_name) values ('European Molecular Biology Laboratory \(Monterotondo\)');
insert into tag (tag_name) values ('Fraunhofer Heinrich Hertz Institut');
insert into tag (tag_name) values ('Goldsmiths\, University of London');
insert into tag (tag_name) values ('Heriot-Watt University');
insert into tag (tag_name) values ('Horizons University');
insert into tag (tag_name) values ('Imperial College London');
insert into tag (tag_name) values ('IMT Institute for Advanced Studies Lucca');
insert into tag (tag_name) values ('INRS-EMT');
insert into tag (tag_name) values ('Institut Laue-Langevin');
insert into tag (tag_name) values ('Institute of Education\, University of London');
insert into tag (tag_name) values ('ISI Foundation');
insert into tag (tag_name) values ('John Innes Centre');
insert into tag (tag_name) values ('Keele University');
insert into tag (tag_name) values ('King\'s College London');
insert into tag (tag_name) values ('Kingston University');
insert into tag (tag_name) values ('KU Leuven');
insert into tag (tag_name) values ('Kyushu University');
insert into tag (tag_name) values ('Lancaster University');
insert into tag (tag_name) values ('Leeds Metropolitan University');
insert into tag (tag_name) values ('Life Science Zurich Graduate School');
insert into tag (tag_name) values ('Liverpool John Moores University');
insert into tag (tag_name) values ('London School of Economics and Political Science');
insert into tag (tag_name) values ('London South Bank University');
insert into tag (tag_name) values ('Loughborough University');
insert into tag (tag_name) values ('Macquarie University');
insert into tag (tag_name) values ('Manchester Metropolitan University');
insert into tag (tag_name) values ('Max Planck');
insert into tag (tag_name) values ('Medical Research Council \(Cambridge\)');
insert into tag (tag_name) values ('Medical Research Council \(Nottingham\)');
insert into tag (tag_name) values ('Monash University');
insert into tag (tag_name) values ('Moredun Research Institute');
insert into tag (tag_name) values ('National Institute of Agricultural Botany \(NIAB\)');
insert into tag (tag_name) values ('National University of Singapore');
insert into tag (tag_name) values ('Newcastle University');
insert into tag (tag_name) values ('NHH - The Norwegian School of Economics and Business Administration');
insert into tag (tag_name) values ('Northumbria University');
insert into tag (tag_name) values ('Nottingham Trent University');
insert into tag (tag_name) values ('Open University');
insert into tag (tag_name) values ('Oxford Brookes University');
insert into tag (tag_name) values ('Politecnico di Milano');
insert into tag (tag_name) values ('Public Health England');
insert into tag (tag_name) values ('Queen Mary\, University of London');
insert into tag (tag_name) values ('Queen\'s University Belfast');
insert into tag (tag_name) values ('Queensland University of Technology');
insert into tag (tag_name) values ('Royal Holloway\, University of London');
insert into tag (tag_name) values ('School of Advanced Study');
insert into tag (tag_name) values ('Science and Technology Facilities Council');
insert into tag (tag_name) values ('SRUC - Scotland\'s Rural College');
insert into tag (tag_name) values ('Swansea University');
insert into tag (tag_name) values ('Syracuse University');
insert into tag (tag_name) values ('Teesside University');
insert into tag (tag_name) values ('The Genome Analysis Centre');
insert into tag (tag_name) values ('The James Hutton Institute');
insert into tag (tag_name) values ('Trinity College Dublin');
insert into tag (tag_name) values ('United Nations University');
insert into tag (tag_name) values ('Università degli Studi Mediterranea di Reggio Calabria');
insert into tag (tag_name) values ('Universität Bonn');
insert into tag (tag_name) values ('Université de Sherbrooke');
insert into tag (tag_name) values ('Université de Toulouse');
insert into tag (tag_name) values ('University College Dublin');
insert into tag (tag_name) values ('University College London');
insert into tag (tag_name) values ('University of Arkansas');
insert into tag (tag_name) values ('University of Auckland');
insert into tag (tag_name) values ('University of Bath');
insert into tag (tag_name) values ('University of Bern');
insert into tag (tag_name) values ('University of Birmingham');
insert into tag (tag_name) values ('University of Bristol');
insert into tag (tag_name) values ('University of Calgary');
insert into tag (tag_name) values ('University of Cambridge');
insert into tag (tag_name) values ('University of Canterbury');
insert into tag (tag_name) values ('University of Copenhagen');
insert into tag (tag_name) values ('University of Derby');
insert into tag (tag_name) values ('University of Dundee');
insert into tag (tag_name) values ('University of East Anglia');
insert into tag (tag_name) values ('University of Edinburgh');
insert into tag (tag_name) values ('University of Essex');
insert into tag (tag_name) values ('University of Exeter');
insert into tag (tag_name) values ('University of Genoa');
insert into tag (tag_name) values ('University of Glasgow');
insert into tag (tag_name) values ('University of Greenwich');
insert into tag (tag_name) values ('University of Hull');
insert into tag (tag_name) values ('University of Kent');
insert into tag (tag_name) values ('University of Koblenz-Landau');
insert into tag (tag_name) values ('University of Leeds');
insert into tag (tag_name) values ('University of Leicester');
insert into tag (tag_name) values ('University of Lincoln');
insert into tag (tag_name) values ('University of Liverpool');
insert into tag (tag_name) values ('University of London');
insert into tag (tag_name) values ('University of Luxembourg');
insert into tag (tag_name) values ('University of Macedonia');
insert into tag (tag_name) values ('University of Manchester');
insert into tag (tag_name) values ('University of Milan');
insert into tag (tag_name) values ('University of Nottingham');
insert into tag (tag_name) values ('University of Otago');
insert into tag (tag_name) values ('University of Oxford');
insert into tag (tag_name) values ('University of Portsmouth');
insert into tag (tag_name) values ('University of Reading');
insert into tag (tag_name) values ('University of Roehampton');
insert into tag (tag_name) values ('University of Salford');
insert into tag (tag_name) values ('University of Sheffield');
insert into tag (tag_name) values ('University of South Wales');
insert into tag (tag_name) values ('University of Southampton');
insert into tag (tag_name) values ('University of St Andrews');
insert into tag (tag_name) values ('University of Stirling');
insert into tag (tag_name) values ('University of Strathclyde');
insert into tag (tag_name) values ('University of Sunderland');
insert into tag (tag_name) values ('University of Surrey');
insert into tag (tag_name) values ('University of Sussex');
insert into tag (tag_name) values ('University of Tartu');
insert into tag (tag_name) values ('University of the Highlands and Islands');
insert into tag (tag_name) values ('University of the West of Scotland');
insert into tag (tag_name) values ('University of the Western Cape');
insert into tag (tag_name) values ('University of Tübingen');
insert into tag (tag_name) values ('University of Ulster');
insert into tag (tag_name) values ('University of Warwick');
insert into tag (tag_name) values ('University of Western Australia');
insert into tag (tag_name) values ('University of Western Sydney');
insert into tag (tag_name) values ('University of Wolverhampton');
insert into tag (tag_name) values ('University of York');
insert into tag (tag_name) values ('University of Zurich');
insert into tag (tag_name) values ('Utah State University\, USA');
insert into tag (tag_name) values ('Victoria University of Wellington');
insert into tag (tag_name) values ('Waterford Institute of Technology');
insert into tag (tag_name) values ('World Maritime University');
insert into tag (tag_name) values ('Xi\'an Jiaotong-Liverpool University');
insert into tag (tag_name) values ('York St John University');
